# This is a format job. Pre-commit has a first-party GitHub action, so we use
# that: https://github.com/pre-commit/action

name: Formatting (pre-commit)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - ros2

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: pre-commit/action@v3.0.1
